version: 2.1

orbs:
    codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test -Pheadless=true
